# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'pim/kmime': '@same'

Options:
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 tests-run-in-parallel: True
